version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/core"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
  - package-ecosystem: "pip"
    directory: "/nightwatch"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
  - package-ecosystem: "pip"
    directory: "/daydream"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
  - package-ecosystem: "pip"
    directory: "/lucid"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
  - package-ecosystem: "pip"
    directory: "/warden"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
